/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Model.Model;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class View extends javax.swing.JFrame {

    private int xMouse;
    private int yMouse;
//    private int width;
//    private int height;

    public View() {
        initComponents();
//        position();
    }

//    public void position() {
//        width = (Toolkit.getDefaultToolkit().getScreenSize().width / 2);
//        height = (Toolkit.getDefaultToolkit().getScreenSize().height / 2);
//        this.setLocation(width, height);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBg1 = new javax.swing.JLabel();
        lblBg5 = new javax.swing.JLabel();
        lblBg4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        lblTextTitle1 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnEnter1 = new javax.swing.JButton();
        txtName3 = new javax.swing.JTextField();
        txtName4 = new javax.swing.JTextField();

        lblBg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thjava/helloworld/img/bg.png"))); // NOI18N
        lblBg1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBg1MouseDragged(evt);
            }
        });
        lblBg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBg1MousePressed(evt);
            }
        });

        lblBg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thjava/helloworld/img/bg.png"))); // NOI18N
        lblBg5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBg5MouseDragged(evt);
            }
        });
        lblBg5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBg5MousePressed(evt);
            }
        });

        lblBg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thjava/helloworld/img/bg.png"))); // NOI18N
        lblBg4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBg4MouseDragged(evt);
            }
        });
        lblBg4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBg4MousePressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblX.setForeground(new java.awt.Color(193, 0, 50));
        lblX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblX.setText("x");
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
        });
        jPanel1.add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 20, -1));

        lblTextTitle1.setForeground(new java.awt.Color(104, 30, 126));
        lblTextTitle1.setText("Enter your Code:");
        jPanel1.add(lblTextTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 260, -1));

        btnClear.setBackground(new java.awt.Color(254, 197, 222));
        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(193, 0, 50));
        btnClear.setText("Clear");
        btnClear.setBorder(null);
        btnClear.setFocusPainted(false);
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 80, 40));

        btnEnter1.setBackground(new java.awt.Color(177, 231, 223));
        btnEnter1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEnter1.setForeground(new java.awt.Color(0, 101, 68));
        btnEnter1.setText("Enter");
        btnEnter1.setBorder(null);
        btnEnter1.setFocusPainted(false);
        jPanel1.add(btnEnter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 80, 40));

        txtName3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName3.setForeground(new java.awt.Color(0, 117, 58));
        txtName3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName3.setBorder(null);
        txtName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName3ActionPerformed(evt);
            }
        });
        jPanel1.add(txtName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 260, 40));

        txtName4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName4.setForeground(new java.awt.Color(0, 117, 58));
        txtName4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtName4.setBorder(null);
        txtName4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName4ActionPerformed(evt);
            }
        });
        jPanel1.add(txtName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblXMouseClicked

    private void lblBg1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBg1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBg1MouseDragged

    private void lblBg1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBg1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBg1MousePressed

    private void txtName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName3ActionPerformed

    private void lblBg4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBg4MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBg4MouseDragged

    private void lblBg4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBg4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBg4MousePressed

    private void lblBg5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBg5MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBg5MouseDragged

    private void lblBg5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBg5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBg5MousePressed

    private void txtName4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName4ActionPerformed

    public JButton getBtnClear() {
        return btnClear;
    }

    public JButton getBtnEnter1() {
        return btnEnter1;
    }


    public JTextField getTxtName3() {
        return txtName3;
    }

    public void show(Model m){
        txtName4.setText(m.getOrder());
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEnter1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBg1;
    private javax.swing.JLabel lblBg4;
    private javax.swing.JLabel lblBg5;
    private javax.swing.JLabel lblTextTitle1;
    private javax.swing.JLabel lblX;
    private javax.swing.JTextField txtName3;
    private javax.swing.JTextField txtName4;
    // End of variables declaration//GEN-END:variables
}
